const refs = {
  openTeam: document.querySelector('.footer__link'),
  filmsList: document.querySelector('#films-section'),
  dataContainer: document.querySelector('#dataContainer'),
  backdropClick: document.querySelector('.backdrop'),
  openModal: document.querySelector('.films'),
  body: document.querySelector('body'),
  closeModalBtn: document.querySelector('.button-close'),
  spinnerInModal: document.querySelector('.spinnerInModal'),
  searchForm: document.querySelector('#search-form'),
  spinner: document.querySelector('.spinner'),
  dataContainer: document.querySelector('#dataContainer'),
  home: document.querySelector('#home'),
  myLibrary: document.querySelector('#library'),
  homepage: document.querySelector('.nav__homePage'),
  libraryPage: document.querySelector('.header__buttons'),
  logo: document.querySelector('#logo'),
  header: document.querySelector('.header'),
  error: document.querySelector('.nav__error'),
  queue: document.querySelector('#queue'),
  watched: document.querySelector('#watched'),
  modal: document.querySelector('.modal'),
  paginator: document.querySelector('#pagination-container'),
  notification: document.querySelector('.notification'),
  theme: document.querySelector('.theme-switch__title'),
  remove: document.querySelector('#remove'),
};

export default refs;
